config/routes.rb
Moneta::Application.routes.draw do
  devise_for :users

  resources :accounts do
    resources :tracks
  end
  resources :categories

  root :to => 'accounts#show', :id => '1'

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :tracks
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tracks

  scope :income, where(exchange_type: "income")
  scope :outcome, where(exchange_type: "outcome")
end

app/models/property.rb
class Property < ActiveRecord::Base
  has_many :tracks
  
  def is_setted?
    true
    unless Property.where("value is not null").count == 0
      false
    end
  end
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :account, :counter_cache => true
  belongs_to :category

  scope :order_by_date, order("exchange_date DESC")
  #scope :date_filter, lambda { |start_date, end_date| where("exchange_date between ? and ?", start_date, end_date) }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
before_filter :authenticate_user!

def index
  @accounts = Account.all
end

def show
  @accounts = Account.all
  @account = Account.find(params[:id])
  @categories = Category.all
  
  #篩選用  
  @start_date = params[:start_date] || ''
  @end_date = params[:end_date] || ''

  if @start_date!=''
    @tracks = @account.tracks.where("exchange_date >= ?", @start_date)
    @status = 'start'
    if @end_date!=''
      @tracks = @account.tracks.where("exchange_date >= ? AND exchange_date <= ?", @start_date, @end_date)
      @status = 'both'
    end
  elsif @end_date!=''
    @tracks = @account.tracks.where("exchange_date <= ?", @end_date)
    @status = 'end'
  else
    @tracks = @account.tracks
    @status = 'none'
  end

  #統計圖表用
  @category_statistics = @categories.map { |c| %{["#{c.name}",#{@tracks.where("category_id == ?", c.id).size}]}}.join(',')

  #排序和分頁
  @tracks = @tracks.order_by_date.paginate(:page => params[:page], :per_page => 10 )
end

def new
  @account = Account.new
end

def create
  @account = Account.create(params[:account])

  redirect_to accounts_path
end

def edit
  @account = Account.find(params[:id])
end

def update
  @account = Account.find(params[:id])
  @account = Account.update_attributes(params[:account])

  redirect_to accounts_path
end

def destroy
  @account = Account.find(params[:id])
  @account.destroy
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
    @outcome_categories = Category.outcome
    @income_categories = Category.income
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new

  end

  def create
    @category = Category.create(params[:category])

    redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update_attributes(params[:category])

    redirect_to tracks_path
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to tracks_path
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    @properties = Property.all
  end
  def new
    @property = Property.new
  end
  def create
    @property = Property.create(params[:property])
    @property.save
    redirect_to properties_path
  end
  def edit
    @property = Property.find(params[:id])
  end
  def update
    @property = Property.find(params[:id])
    @property.update_attributes(params[:property])
    redirect_to properties_path
  end
  def destroy
    @property = Property.find(params[:id])
    @property.destroy
    
    redirect_to properties_path
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  layout "plain", :only => [:new, :edit]

  def index
    @account = Account.find(params[:account_id])
    redirect_to account_path(@account)
  end
  def show
    @account = Account.find(params[:account_id])
    @track = @account.tracks.find(params[:id])
  end
  def new
    @account = Account.find(params[:account_id])
    @track = @account.tracks.build
    @outcome_categories = Category.outcome
    @income_categories = Category.income
  end
  def create
    @account = Account.find(params[:account_id])
    @track = @account.tracks.build(params[:track])
    if @track.save
      redirect_to account_path(@account)
    end
  end
  def edit
    @account = Account.find(params[:account_id])
    @track = @account.tracks.find(params[:id])
    @outcome_categories = Category.outcome
    @income_categories = Category.income
  end
  def update
    @account = Account.find(params[:account_id])
    @track = @account.tracks.find(params[:id])
    if @track.update_attributes(params[:track])
      redirect_to account_path(@account)
    end
  end
  def destroy
    @account = Account.find(params[:account_id])
    @track = @account.tracks.find(params[:id])
    if @track.destroy 
      redirect_to account_path(@account)
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/accounts/_form.html.erb
<%= f.label :name, "帳戶名稱：" %>
<%= f.text_field :name %>
<br />

app/views/accounts/edit.html.erb
<h1>編輯帳戶</h1>
<%= form_for @account do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
  <%= f.submit "修改" %>
<% end %>

app/views/accounts/index.html.erb
<h2>帳戶列表</h2>

<% if @accounts.length > 0 %>
<ul>
  <% @accounts.each do |account| %>
  <li><%= link_to account.name, account_path(account) %></li>
  <% end %>
</ul>
<% end %>

<%= link_to '設定新帳戶', new_account_path %>

app/views/accounts/new.html.erb
<h1>加入新分類</h1>
<%= form_for @account do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
  <%= f.submit "新增" %>
<% end %>
<%= link_to '不想加了', categories_path %>

app/views/accounts/show.html.erb
<% content_for :side do %>
<h4>現有帳戶</h4>
<ul>
  <% @accounts.each do |account| %>
  <li><%= link_to account.name, account_path(account) %></li>
  <% end %>
</ul>
<%= link_to '新增帳戶', new_account_path %>

<div class="well">
<%= form_tag url_for(action: 'show', controller: 'accounts'), :method => "get" do %>
  <%= text_field_tag 'start_date', nil, :class => 'datepicker' %>
  <%= text_field_tag 'end_date', nil, :class => 'datepicker' %>
  <%= hidden_field_tag "id", @account.id %>
  <%= submit_tag '篩選' %>
  <%= link_to '恢復預設', account_path %>
<% end %>

<br />
<%= @status %>
<%= @start_date %>
<%= @end_date %>

<a href="#" id="view_graph">看圖表</a>
<a href="#" id="view_list">回列表</a>
</div>
<% end %>

<h2><%= @account.name %> (<%= link_to '編輯', edit_account_path(@account) %>)</h2>

<div id="list_block">
<div class="well main_form">
  <div id="track_form">
  </div>
</div>
<table class="table">
  <tr>
    <th>日期</th>
    <th>分類</th>
    <th>價格</th>
    <th>明細</th>
    <th></th>
    <th></th>
  </tr>
<% @tracks.each do |track| %>
  <tr>
    <td><%= track.exchange_date %></td>
    <td><%= track.category.name if (track.category_id) %></td>
    <td><%= number_to_currency(track.price, :locale => :tw, :precision => 0) %></td>
    <td><%= track.description %></td>
    <td><%= link_to "編輯", edit_account_track_path(@account,track), :class => 'edit_track' %></td>
    <td><%= link_to "刪除", account_track_path(@account,track), method: :delete, :confirm => "請確定是否刪除" %></td>
  </tr>
<% end %>
</table>
<%= will_paginate(@tracks)%>
</div>

<div id="graph_block">
  <div id="chart_div"></div>
</div>

<% content_for :js do %>
<script>
$(function() {
  $('#graph_block').hide();
  $('#view_list').hide();
  $('.datepicker').datepicker({dateFormat:"yy-mm-dd"});
  $('#track_form').load('<%= new_account_track_path(@account) %>');
  $('.edit_track').click( function(){
    $('#track_form').load( $(this).attr("href") );
    $('.main_form').effect("highlight", {}, 2000);
    return false;
  });
  $('#view_graph').click(function() {
    $('#list_block').hide();
    $('#graph_block').show();
    $('#view_graph').hide();
    $('#view_list').show();
    return false;
  });
  $('#view_list').click(function() {
    $('#list_block').show();
    $('#graph_block').hide();
    $('#view_graph').show();
    $('#view_list').hide();
    return false;
  });
});

// Load the Visualization API and the piechart package.
google.load('visualization', '1.0', {'packages':['corechart']});

// Set a callback to run when the Google Visualization API is loaded.
google.setOnLoadCallback(drawChart);

// Callback that creates and populates a data table,
// instantiates the pie chart, passes in the data and
// draws it.
function drawChart() {

  // Create the data table.
  var data = new google.visualization.DataTable();
  data.addColumn('string', 'Topping');
  data.addColumn('number', 'Slices');
  data.addRows([<%= raw @category_statistics %>]);

  // Set chart options
  var options = {'width': $('#main_block').width() * 0.8,
                 'height': $('#main_block').width() * 0.6};

  // Instantiate and draw our chart, passing in some options.
  var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
  chart.draw(data, options);
}

</script>
<% end %>

app/views/categories/_form.html.erb
<%= f.label :name, "分類名稱：" %>
<%= f.text_field :name %>
<br />
<%= f.label :exchange_type, "類別：" %>
<%= f.radio_button :exchange_type, 'outcome' %> 支出
<%= f.radio_button :exchange_type, 'income' %> 收入
<br />

app/views/categories/index.html.erb
<h2>分類列表</h2>

<div id="add_category">

</div>
<h3>支出分類</h3>
<% if @outcome_categories.length > 0 %>
<ul>
  <% @outcome_categories.each do |category| %>
  <li><%= category.name %></li>
  <% end %>
</ul>
<% end %>
<h3>收入分類</h3>
<% if @income_categories.length > 0 %>
<ul>
  <% @income_categories.each do |category| %>
  <li><%= category.name %></li>
  <% end %>
</ul>
<% end %>

<%#= link_to '建立新分類', new_category_path %>

<% content_for :js do %>
<script>
    $(document).ready(function() {        
      $('#add_category').load('<%= new_category_path %>');
    });
</script>
<% end %>

app/views/categories/new.html.erb
<h1>加入新分類</h1>
<%= form_for @category do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
  <%= f.submit "新增" %>
<% end %>
<%= link_to '不想加了', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moneta</title>
  <%= stylesheet_link_tag    "application" %>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <div class="container-fluid">
        <a class="brand" href="/">Moneta</a>
        <div class="nav-collapse">
          <ul class="nav pull-right">
            <li><a href="#">報帳頁面</a></li>
            <li><%= link_to '分類設定', categories_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
</div>
<div class="container">
<div class="row">
<div class="span3">
  <%= yield :side %>
</div>
<div class="span9" id="main_block">
<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>
<% if flash[:error] %>
  <p class="error"><%= flash[:error] %></p>
<% end %>
<%= yield %>
</div>
</div>
<%= yield :js %>
</div>
</body>
</html>

app/views/layouts/plain.html.erb
<%= yield %>
<%= yield :js %>

app/views/properties/_form.html.erb
<%= f.label :name, "資產項目：" %>
<%= f.text_field :name %>
<br />
<%= f.label :value, "金額：" %>
<%= f.text_field :value %>
<br />

app/views/properties/edit.html.erb
<h1>修改資產項目</h1>
<%= form_for @property do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
  <%= f.submit "修改" %>
<% end %>
<%= link_to '不想改了', properties_path %>

app/views/properties/index.html.erb
<h2>資產列表</h2>

<table>
  <tr>
    <th>項目</th>
    <th>金額</th>
    <th></th>
    <th></th>
  </tr>
<% @properties.each do |property| %>
  <tr>
    <td><%= property.name %></td>
    <td><%= property.value %></td>
    <td><%= link_to "編輯", edit_property_path(property) %></td>
    <td><%= link_to "刪除", property_path(property), method: :delete, :confirm => "請確定是否刪除" %></td>
  </tr>
<% end %>
</table>

<%= link_to '建立新項目', new_property_path %><br />
<%= link_to '移動到記帳頁面', tracks_path %>

app/views/properties/new.html.erb
<h1>加入新資產項目</h1>
<%= form_for @property do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
  <%= f.submit "新增" %>
<% end %>
<%= link_to '不想加了', properties_path %>

app/views/tracks/_form.html.erb
<%= f.datepicker :exchange_date, :dateFormat => "yy-mm-dd" %>
<% if @track.category.try(:exchange_type) %>
  <input type="radio" name="type" value="outcome" class="type" <%= 'checked' if (@track.category.exchange_type=='outcome') %>> 支出
  <input type="radio" name="type" value="income" class="type" <%= 'checked' if (@track.category.exchange_type=='income') %>> 收入 
  
  <% if (@track.category.exchange_type=='outcome') %>
    <%= f.select :category_id, options_from_collection_for_select(@outcome_categories, :id, :name, @track.category_id) %>
  <% elsif (@track.category.exchange_type=='income') %>
    <%= f.select :category_id, options_from_collection_for_select(@income_categories, :id, :name, @track.category_id) %>
  <% end %>

<% else %>
  <input type="radio" name="type" value="outcome" class="type" checked> 支出
  <input type="radio" name="type" value="income" class="type"> 收入 

  <%= f.select :category_id, options_from_collection_for_select(@outcome_categories, :id, :name) %>
<% end %>

<br />
<%= f.label :price, "價格：", :class => 'inline' %>
<%= f.number_field :price, :class => 'inline' %>
<%= f.label :description, "交易明細：", :class => 'inline' %>
<%= f.text_field :description, :class => 'inline' %>

<% content_for :js do %>
<script>
$(function() {
  $('input.type').click(function() {
    $('#track_category_id').hide();
    $('#track_category_id').html('');
    if ($(this).val()=='outcome') {
      $('#track_category_id').append("<%= escape_javascript(options_from_collection_for_select(@outcome_categories, :id, :name)) %>");
    }
    else if ($(this).val()=='income') {
      $('#track_category_id').append("<%= escape_javascript(options_from_collection_for_select(@income_categories, :id, :name)) %>");
    }
    $('#track_category_id').show();
  });
});
</script>
<% end %>

app/views/tracks/edit.html.erb
<h3>編輯記錄</h3>
<%= form_for [@account, @track], :html => {:class => 'form-inline'} do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
  <%= f.submit "修改" %>
  <%= link_to '取消', account_path(@account) %>
<% end %>

app/views/tracks/index.html.erb
<h2>收支記錄</h2>

<table>
  <tr>
    <th>價格</th>
    <th>明細</th>
    <th></th>
    <th></th>
  </tr>
<% @tracks.each do |track| %>
  <tr>
    <td><%= number_to_currency(track.price, :locale => :tw, :precision => 0) %></td>
    <td><%= track.description %></td>
    <td><%= link_to "編輯", edit_track_path(track) %></td>
    <td><%= link_to "刪除", track_path(track), method: :delete, :confirm => "請確定是否刪除" %></td>
  </tr>
<% end %>
</table>

<%= link_to '建立新記錄', new_track_path %>

app/views/tracks/new.html.erb
<h3>加入新收支記錄</h3>
<%= form_for [@account, @track], :html => {:class => 'form-inline'} do |f|  %>
  <%= render partial: 'form', locals: { f: f } %>
  <%= f.submit "新增" %>
<% end %>